import type {Controls} from '../core/simulation';
export class Controller{
 controls:Controls={mx:0,my:0,aim:null,fire:false,boost:false,brake:false,target:null};private keys=new Set<string>();private left={x:0,y:0};private right:{x:number;y:number}|null=null;private leftId:number|null=null;private rightId:number|null=null;enabled=false;private held={fire:false,boost:false,brake:false};
 constructor(private canvas:HTMLCanvasElement,private toWorld:(x:number,y:number)=>{x:number;y:number},private position:()=>{x:number;y:number},private action:(key:string)=>void,private sensitivity:()=>number){
 window.addEventListener('keydown',e=>{if((e.target as HTMLElement)?.matches('input,textarea,select')||!this.enabled)return;this.keys.add(e.code);if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!e.repeat)this.action(e.code);});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.reset());
 canvas.addEventListener('pointermove',e=>{if(!this.enabled||e.pointerType!=='mouse')return;const p=this.toWorld(e.clientX,e.clientY),s=this.position();this.controls.aim=Math.atan2(p.y-s.y,p.x-s.x);});canvas.addEventListener('pointerdown',e=>{if(!this.enabled)return;if(e.button===2){this.held.fire=true;canvas.setPointerCapture(e.pointerId);return;}const p=this.toWorld(e.clientX,e.clientY);this.action(`target:${p.x}:${p.y}`);});canvas.addEventListener('pointerup',()=>this.held.fire=false);canvas.addEventListener('pointercancel',()=>this.held.fire=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
 }
 attach(){const left=document.getElementById('stick-left')!,right=document.getElementById('stick-right')!;const cancel=(node:HTMLElement)=>{node.querySelector<HTMLElement>('.stick-thumb')!.style.transform='translate(0,0)';};
 left.addEventListener('pointerdown',e=>{if(!this.enabled)return;this.leftId=e.pointerId;left.setPointerCapture(e.pointerId);this.moveStick(e,left,true);});left.addEventListener('pointermove',e=>{if(e.pointerId===this.leftId)this.moveStick(e,left,true);});for(const event of ['pointerup','pointercancel','lostpointercapture'])left.addEventListener(event,e=>{if((e as PointerEvent).pointerId===this.leftId){this.left={x:0,y:0};this.leftId=null;cancel(left);}});
 right.addEventListener('pointerdown',e=>{if(!this.enabled)return;this.rightId=e.pointerId;right.setPointerCapture(e.pointerId);this.moveStick(e,right,false);});right.addEventListener('pointermove',e=>{if(e.pointerId===this.rightId)this.moveStick(e,right,false);});for(const event of ['pointerup','pointercancel','lostpointercapture'])right.addEventListener(event,e=>{if((e as PointerEvent).pointerId===this.rightId){this.right=null;this.rightId=null;cancel(right);this.controls.fire=false;this.controls.aim=null;}});
 const hold=(id:string,field:'fire'|'boost'|'brake')=>{const node=document.getElementById(id)!;node.addEventListener('pointerdown',e=>{if(this.enabled){this.held[field]=true;node.setPointerCapture(e.pointerId);}});for(const event of ['pointerup','pointercancel','lostpointercapture'])node.addEventListener(event,()=>this.held[field]=false);};hold('fire-button','fire');hold('boost-button','boost');hold('brake-button','brake');
 }
 private moveStick(e:PointerEvent,node:HTMLElement,isLeft:boolean){const r=node.getBoundingClientRect(),radius=r.width*.38;let dx=e.clientX-r.x-r.width/2,dy=e.clientY-r.y-r.height/2;const dist=Math.hypot(dx,dy);if(dist>radius){dx*=radius/dist;dy*=radius/dist;}node.querySelector<HTMLElement>('.stick-thumb')!.style.transform=`translate(${dx}px,${dy}px)`;if(isLeft){this.left={x:dx/radius,y:dy/radius};this.controls.target=null;this.controls.aim=null;}else{this.right={x:dx/radius,y:dy/radius};this.controls.aim=Math.atan2(dy,dx);this.controls.fire=dist>radius*.3;}}
 update(){if(!this.enabled){this.controls.mx=0;this.controls.my=0;return;}const x=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0),y=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);this.controls.mx=x||this.left.x*this.sensitivity();this.controls.my=y||this.left.y*this.sensitivity();const n=Math.hypot(this.controls.mx,this.controls.my);if(n>1){this.controls.mx/=n;this.controls.my/=n;}if(x||y){this.controls.target=null;if(!this.right)this.controls.aim=null;}this.controls.fire=this.keys.has('Space')||this.held.fire||(this.rightId!==null&&this.right!==null&&Math.hypot(this.right.x,this.right.y)>.3);this.controls.boost=this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')||this.held.boost;this.controls.brake=this.keys.has('KeyX')||this.held.brake;}
 reset(){this.held={fire:false,boost:false,brake:false};this.keys.clear();this.left={x:0,y:0};this.right=null;this.leftId=null;this.rightId=null;this.controls={mx:0,my:0,aim:null,fire:false,boost:false,brake:false,target:null};}
}
